import type { Metadata } from "next";
// import localFont from "next/font/local";
import {Poppins } from "next/font/google"
import "./globals.css";
import ResponsiveNav from "./components/Navigation/ResponsiveNav";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const poppins =Poppins({
  weight:["400" ,"500","600","700","800"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Agency | Craft Your Dream Journey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}>
          <ResponsiveNav/>
          {children}
      </body>
    </html>
  );
}
